libraries: 
  Movies - 4K:    
    overlays: true # Enable overlays for this library. 'false' will remove existing overlays
    skip: true # Skip this library

  Movies - 4K Dolby Vision:
    overlays: true
    skip: true

  TV Shows - 4K:
    overlays: true
    skip: false

  TV Shows - 4K Dolby Vision:
    overlays: true
    skip: false
