libraries:
  Movies - 4K:
    enabled: false
    overlays: false

  Movies - 4K Dolby Vision:
    enabled: true
    overlays: false

  TV Shows - 4K:
    enabled: false
    overlays: false

  TV Shows - 4K Dolby Vision:
    enabled: false
    overlays: false

Collections:
  Top Movies:
    config_files:
      - "Movies.yaml"
    libraries:
      - "Movies - 4K"
      - "Movies - 4K Dolby Vision"
